In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df = pd.read_csv('student_performance_prediction_dataset-2.csv')

In [45]:
df.head()

,student_id,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,...,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade,grade_category,pass_fail
0,1,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,...,4.018412,Medium,Master,Yes,Mobile,Private,Coding Club,59.248749,D,Pass
1,2,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,...,3.268642,Medium,Master,Yes,Laptop,Public,NaN,58.595595,D,Pass
2,3,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,...,2.327293,Low,High School,Yes,Tablet,Private,Music,85.855289,A,Pass
3,4,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,...,1.163367,Medium,Bachelor,Yes,Laptop,Public,Debate,42.117503,F,Fail
4,5,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,...,0.411183,High,High School,Yes,Laptop,Private,Debate,62.870474,C,Pass

In [46]:
df.shape

(300000, 25)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 25 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   student_id             300000 non-null  int64
 1   age                    300000 non-null  int64
 2   gender                 300000 non-null  object
 3   study_hours            300000 non-null  float64
 4   attendance             300000 non-null  float64
 5   sleep_hours            300000 non-null  float64
 6   previous_grade         300000 non-null  float64
 7   assignments_completed  300000 non-null  float64
 8   practice_tests_taken   300000 non-null  float64
 9   group_study_hours      300000 non-null  float64
 10  notes_quality_score    300000 non-null  float64
 11  time_management_score  300000 non-null  float64
 12  motivation_level       300000 non-null  float64
 13  mental_health_score    300000 non-null  float64
 14  screen_time            300000 non-null  float64
 15  social_media_hours     300000 non-null  float64
 16  family_income          300000 non-null  object
 17  parent_education       300000 non-null  object
 18  internet_access        300000 non-null  object
 19  device_type            284895 non-null  object
 20  school_type            300000 non-null  object
 21  extracurriculars       250019 non-null  object
 22  final_grade            300000 non-null  float64
 23  grade_category         299996 non-null  object
 24  pass_fail              300000 non-null  object
dtypes: float64(14), int64(2), object(9)
memory usage: 57.2+ MB

In [48]:
df.columns

Index(['student_id', 'age', 'gender', 'study_hours', 'attendance',
       'sleep_hours', 'previous_grade', 'assignments_completed',
       'practice_tests_taken', 'group_study_hours', 'notes_quality_score',
       'time_management_score', 'motivation_level', 'mental_health_score',
       'screen_time', 'social_media_hours', 'family_income',
       'parent_education', 'internet_access', 'device_type', 'school_type',
       'extracurriculars', 'final_grade', 'grade_category', 'pass_fail'],
      dtype='object')

In [49]:
df.isnull().sum()

student_id                   0
age                          0
gender                       0
study_hours                  0
attendance                   0
sleep_hours                  0
previous_grade               0
assignments_completed        0
practice_tests_taken         0
group_study_hours            0
notes_quality_score          0
time_management_score        0
motivation_level             0
mental_health_score          0
screen_time                  0
social_media_hours           0
family_income                0
parent_education             0
internet_access              0
device_type              15105
school_type                  0
extracurriculars         49981
final_grade                  0
grade_category               4
pass_fail                    0
dtype: int64

In [50]:
df['device_type']=df['device_type'].fillna(df['device_type'].mode()[0])

In [51]:
df['extracurriculars']=df['extracurriculars'].fillna('Unknown')

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df = df.drop(columns=['student_id','grade_category','pass_fail'],axis=1)

In [54]:
df.select_dtypes(include ='object').nunique()

gender              3
family_income       3
parent_education    4
internet_access     2
device_type         3
school_type         2
extracurriculars    6
dtype: int64

In [55]:
df['family_income'].unique()

array(['Medium', 'Low', 'High'], dtype=object)

In [56]:
df['parent_education'].unique()

array(['Master', 'High School', 'Bachelor', 'PhD'], dtype=object)

In [57]:
df['internet_access'].unique()

array(['Yes', 'No'], dtype=object)

In [58]:
df['school_type'].unique()

array(['Private', 'Public'], dtype=object)

In [59]:
df['internet_access'] = df['internet_access'].map({'Yes' : 1 , 'No': 0})

In [60]:
df['school_type'] = df['school_type'].map({'Private' : 1 , 'Public': 0})

In [61]:
df.head()

,age,gender,study_hours,attendance,sleep_hours,previous_grade,assignments_completed,practice_tests_taken,group_study_hours,notes_quality_score,...,mental_health_score,screen_time,social_media_hours,family_income,parent_education,internet_access,device_type,school_type,extracurriculars,final_grade
0,21,Male,1.645404,79.154521,8.230886,96.053840,7.719620,1.871170,1.447894,6.811654,...,7.762145,1.549443,4.018412,Medium,Master,1,Mobile,1,Coding Club,59.248749
1,18,Male,4.462126,72.526685,6.139219,53.024821,6.754758,5.630071,1.891288,10.000000,...,4.229670,5.458155,3.268642,Medium,Master,1,Laptop,0,Unknown,58.595595
2,19,Female,6.220212,98.531716,6.946313,78.775422,10.000000,7.862877,1.774356,6.484908,...,7.583075,0.000000,2.327293,Low,High School,1,Tablet,1,Music,85.855289
3,21,Female,1.826644,97.731245,8.297048,76.122618,7.440486,2.316252,1.204271,6.057978,...,4.978907,5.325794,1.163367,Medium,Bachelor,1,Laptop,0,Debate,42.117503
4,17,Male,3.789322,78.589107,6.777171,81.305681,9.962609,5.335697,1.399230,9.013332,...,5.677695,4.416843,0.411183,High,High School,1,Laptop,1,Debate,62.870474

In [62]:
df = pd.get_dummies(df,columns=['gender','device_type','extracurriculars'], dtype=int)

In [63]:
df.columns

Index(['age', 'study_hours', 'attendance', 'sleep_hours', 'previous_grade',
       'assignments_completed', 'practice_tests_taken', 'group_study_hours',
       'notes_quality_score', 'time_management_score', 'motivation_level',
       'mental_health_score', 'screen_time', 'social_media_hours',
       'family_income', 'parent_education', 'internet_access', 'school_type',
       'final_grade', 'gender_Female', 'gender_Male', 'gender_Other',
       'device_type_Laptop', 'device_type_Mobile', 'device_type_Tablet',
       'extracurriculars_Arts', 'extracurriculars_Coding Club',
       'extracurriculars_Debate', 'extracurriculars_Music',
       'extracurriculars_Sports', 'extracurriculars_Unknown'],
      dtype='object')

In [64]:
df['family_income'].unique()

array(['Medium', 'Low', 'High'], dtype=object)

In [65]:
df['parent_education'].unique()

array(['Master', 'High School', 'Bachelor', 'PhD'], dtype=object)

In [66]:
df['parent_education'] = df['parent_education'].map({'High School' : 1 , 'Bachelor': 2,'Master':3 ,'PhD':4})

In [67]:
df['family_income'] = df['family_income'].map({'Low' : 1 , 'Medium': 2,'High':3})

In [68]:
df.dtypes

age                               int64
study_hours                     float64
attendance                      float64
sleep_hours                     float64
previous_grade                  float64
assignments_completed           float64
practice_tests_taken            float64
group_study_hours               float64
notes_quality_score             float64
time_management_score           float64
motivation_level                float64
mental_health_score             float64
screen_time                     float64
social_media_hours              float64
family_income                     int64
parent_education                  int64
internet_access                   int64
school_type                       int64
final_grade                     float64
gender_Female                     int64
gender_Male                       int64
gender_Other                      int64
device_type_Laptop                int64
device_type_Mobile                int64
device_type_Tablet                int64
extracurriculars_Arts             int64
extracurriculars_Coding Club      int64
extracurriculars_Debate           int64
extracurriculars_Music            int64
extracurriculars_Sports           int64
extracurriculars_Unknown          int64
dtype: object

In [69]:
X = df.drop(columns=['final_grade'])
y = df['final_grade']

In [70]:
X.shape

(300000, 30)

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2 ,random_state=42)

In [72]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [73]:
X_train_scaled.mean()

np.float64(-7.837089002451749e-17)

In [74]:
X_test_scaled.std()

np.float64(0.9998778381497105)

In [75]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [76]:
model = keras.Sequential([Dense(64, activation="relu" , input_shape=(X_train_scaled.shape[1],)),
                          Dense(32, activation="relu" ),
                          Dense(16, activation="relu" ),
                          Dense(1)])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [77]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [78]:
model.compile(optimizer="adam" , loss="mse" , metrics=['mae'])

In [79]:
history = model.fit(X_train_scaled, y_train ,epochs=20 ,batch_size=32, validation_split=0.2)

Epoch 1/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 66.9060 - mae: 5.1049 - val_loss: 27.1033 - val_mae: 4.1549
Epoch 2/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.5511 - mae: 4.1110 - val_loss: 26.4305 - val_mae: 4.1017
Epoch 3/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 26.1120 - mae: 4.0765 - val_loss: 26.3112 - val_mae: 4.0930
Epoch 4/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.9240 - mae: 4.0640 - val_loss: 27.1387 - val_mae: 4.1562
Epoch 5/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.8067 - mae: 4.0526 - val_loss: 26.7002 - val_mae: 4.1175
Epoch 6/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 28s 5ms/step - loss: 25.7669 - mae: 4.0517 - val_loss: 25.8402 - val_mae: 4.0543
Epoch 7/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 38s 6ms/step - loss: 25.6977 - mae: 4.0450 - val_loss: 26.4475 - val_mae: 4.1019
Epoch 8/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 25s 4ms/step - loss: 25.6394 - mae: 4.0405 - val_loss: 25.9162 - val_mae: 4.0625
Epoch 9/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 38s 6ms/step - loss: 25.5726 - mae: 4.0337 - val_loss: 25.8293 - val_mae: 4.0543
Epoch 10/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - loss: 25.5529 - mae: 4.0366 - val_loss: 25.7193 - val_mae: 4.0437
Epoch 11/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 22s 4ms/step - loss: 25.5325 - mae: 4.0335 - val_loss: 25.8931 - val_mae: 4.0605
Epoch 12/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 53s 6ms/step - loss: 25.5248 - mae: 4.0310 - val_loss: 26.2331 - val_mae: 4.0829
Epoch 13/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - loss: 25.4710 - mae: 4.0284 - val_loss: 26.3410 - val_mae: 4.0932
Epoch 14/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 36s 4ms/step - loss: 25.4506 - mae: 4.0248 - val_loss: 25.8047 - val_mae: 4.0549
Epoch 15/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.4196 - mae: 4.0218 - val_loss: 25.6073 - val_mae: 4.0360
Epoch 16/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.3843 - mae: 4.0204 - val_loss: 25.7542 - val_mae: 4.0492
Epoch 17/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 26s 4ms/step - loss: 25.3400 - mae: 4.0168 - val_loss: 25.7083 - val_mae: 4.0426
Epoch 18/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 31s 5ms/step - loss: 25.3477 - mae: 4.0179 - val_loss: 25.9244 - val_mae: 4.0600
Epoch 19/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 28s 3ms/step - loss: 25.3352 - mae: 4.0163 - val_loss: 26.1117 - val_mae: 4.0777
Epoch 20/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.3122 - mae: 4.0143 - val_loss: 26.2938 - val_mae: 4.0892

In [80]:
model2 = keras.Sequential([Dense(64, activation='tanh', input_shape=(X_train_scaled.shape[1],)),
                           Dense(32, activation='tanh'),
                           Dense(16, activation='tanh'),
                           Dense(1)])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [81]:
model2.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [82]:
model2.compile(optimizer='sgd', loss='mse', metrics=['mae'])

In [83]:
history2 = model2.fit(X_train_scaled, y_train ,epochs=20 ,batch_size=32, validation_split=0.2)

Epoch 1/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 34.1766 - mae: 4.5090 - val_loss: 28.2842 - val_mae: 4.2321
Epoch 2/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 28.3567 - mae: 4.2450 - val_loss: 28.3394 - val_mae: 4.2396
Epoch 3/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 27.8283 - mae: 4.2002 - val_loss: 27.9170 - val_mae: 4.2136
Epoch 4/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 27.3711 - mae: 4.1717 - val_loss: 27.4353 - val_mae: 4.1782
Epoch 5/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 27.2379 - mae: 4.1606 - val_loss: 27.6786 - val_mae: 4.1988
Epoch 6/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 27.1057 - mae: 4.1536 - val_loss: 28.2123 - val_mae: 4.2341
Epoch 7/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 27.2091 - mae: 4.1585 - val_loss: 28.6395 - val_mae: 4.2689
Epoch 8/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 27.0515 - mae: 4.1468 - val_loss: 27.8587 - val_mae: 4.2039
Epoch 9/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.9117 - mae: 4.1345 - val_loss: 27.4612 - val_mae: 4.1778
Epoch 10/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.8051 - mae: 4.1286 - val_loss: 27.7669 - val_mae: 4.2033
Epoch 11/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.7717 - mae: 4.1260 - val_loss: 27.4067 - val_mae: 4.1728
Epoch 12/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.7471 - mae: 4.1270 - val_loss: 27.2416 - val_mae: 4.1576
Epoch 13/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.7283 - mae: 4.1244 - val_loss: 27.5583 - val_mae: 4.1778
Epoch 14/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 26.7532 - mae: 4.1215 - val_loss: 27.4905 - val_mae: 4.1832
Epoch 15/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.6177 - mae: 4.1177 - val_loss: 27.8881 - val_mae: 4.2059
Epoch 16/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.7941 - mae: 4.1273 - val_loss: 27.6961 - val_mae: 4.1975
Epoch 17/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.7113 - mae: 4.1225 - val_loss: 27.4220 - val_mae: 4.1742
Epoch 18/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.6339 - mae: 4.1166 - val_loss: 27.9480 - val_mae: 4.2091
Epoch 19/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.6030 - mae: 4.1120 - val_loss: 27.4611 - val_mae: 4.1805
Epoch 20/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 26.5086 - mae: 4.1035 - val_loss: 27.4078 - val_mae: 4.1725

In [84]:
model3 = keras.Sequential([Dense(64, activation='sigmoid', input_shape=(X_train_scaled.shape[1],)),
                           Dense(32, activation='sigmoid'),
                           Dense(16, activation='sigmoid'),
                           Dense(1)])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [87]:
model3.compile(optimizer='rmsprop', loss='mse', metrics=['mae'])

In [88]:
history3 = model3.fit(X_train_scaled, y_train ,epochs=20 ,batch_size=32, validation_split=0.2)

Epoch 1/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 679.0872 - mae: 19.9143 - val_loss: 149.6520 - val_mae: 9.7527
Epoch 2/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7271 - mae: 9.7681 - val_loss: 149.5975 - val_mae: 9.7502
Epoch 3/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7231 - mae: 9.7679 - val_loss: 149.6302 - val_mae: 9.7502
Epoch 4/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7349 - mae: 9.7684 - val_loss: 149.5988 - val_mae: 9.7496
Epoch 5/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 149.7255 - mae: 9.7682 - val_loss: 149.6167 - val_mae: 9.7499
Epoch 6/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7276 - mae: 9.7679 - val_loss: 149.5926 - val_mae: 9.7499
Epoch 7/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7270 - mae: 9.7683 - val_loss: 149.6098 - val_mae: 9.7498
Epoch 8/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7285 - mae: 9.7684 - val_loss: 149.6581 - val_mae: 9.7509
Epoch 9/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7311 - mae: 9.7683 - val_loss: 149.6012 - val_mae: 9.7497
Epoch 10/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7230 - mae: 9.7683 - val_loss: 149.5991 - val_mae: 9.7504
Epoch 11/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7296 - mae: 9.7684 - val_loss: 149.5915 - val_mae: 9.7498
Epoch 12/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7273 - mae: 9.7683 - val_loss: 149.5939 - val_mae: 9.7500
Epoch 13/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 17s 3ms/step - loss: 149.7298 - mae: 9.7684 - val_loss: 149.5925 - val_mae: 9.7499
Epoch 14/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7245 - mae: 9.7680 - val_loss: 149.6161 - val_mae: 9.7512
Epoch 15/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7237 - mae: 9.7680 - val_loss: 149.5915 - val_mae: 9.7497
Epoch 16/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7257 - mae: 9.7681 - val_loss: 149.5990 - val_mae: 9.7503
Epoch 17/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7271 - mae: 9.7682 - val_loss: 149.6030 - val_mae: 9.7497
Epoch 18/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 149.7298 - mae: 9.7682 - val_loss: 149.5966 - val_mae: 9.7502
Epoch 19/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7275 - mae: 9.7678 - val_loss: 149.6082 - val_mae: 9.7498
Epoch 20/20
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 149.7352 - mae: 9.7685 - val_loss: 149.5934 - val_mae: 9.7496

In [91]:
model4 = keras.Sequential([Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
                           Dense(32, activation='relu'),
                           Dense(16, activation='relu'),
                           Dense(1)])

In [93]:
model4.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [94]:
history4 = model4.fit(X_train_scaled, y_train ,epochs=50 ,batch_size=32, validation_split=0.2)

Epoch 1/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 58.9876 - mae: 4.9731 - val_loss: 27.3262 - val_mae: 4.1709
Epoch 2/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 26.5883 - mae: 4.1157 - val_loss: 28.6088 - val_mae: 4.2697
Epoch 3/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 26.2204 - mae: 4.0873 - val_loss: 26.0093 - val_mae: 4.0696
Epoch 4/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.9689 - mae: 4.0688 - val_loss: 26.3722 - val_mae: 4.1010
Epoch 5/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.8654 - mae: 4.0580 - val_loss: 26.5710 - val_mae: 4.1099
Epoch 6/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.8035 - mae: 4.0537 - val_loss: 27.0325 - val_mae: 4.1475
Epoch 7/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.7451 - mae: 4.0499 - val_loss: 26.3435 - val_mae: 4.0968
Epoch 8/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.6886 - mae: 4.0441 - val_loss: 26.4392 - val_mae: 4.1026
Epoch 9/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.6442 - mae: 4.0406 - val_loss: 25.9623 - val_mae: 4.0669
Epoch 10/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.6225 - mae: 4.0391 - val_loss: 25.9194 - val_mae: 4.0614
Epoch 11/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.5788 - mae: 4.0371 - val_loss: 25.7245 - val_mae: 4.0473
Epoch 12/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.5781 - mae: 4.0378 - val_loss: 25.7182 - val_mae: 4.0454
Epoch 13/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.5371 - mae: 4.0335 - val_loss: 25.9202 - val_mae: 4.0599
Epoch 14/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.5056 - mae: 4.0324 - val_loss: 25.6686 - val_mae: 4.0424
Epoch 15/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.4676 - mae: 4.0263 - val_loss: 25.9572 - val_mae: 4.0655
Epoch 16/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.4361 - mae: 4.0231 - val_loss: 25.9031 - val_mae: 4.0609
Epoch 17/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.4329 - mae: 4.0225 - val_loss: 25.8182 - val_mae: 4.0540
Epoch 18/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.4196 - mae: 4.0230 - val_loss: 25.8063 - val_mae: 4.0525
Epoch 19/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.3901 - mae: 4.0212 - val_loss: 25.6576 - val_mae: 4.0420
Epoch 20/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.3679 - mae: 4.0182 - val_loss: 26.2136 - val_mae: 4.0830
Epoch 21/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.3398 - mae: 4.0167 - val_loss: 25.5769 - val_mae: 4.0340
Epoch 22/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.3642 - mae: 4.0194 - val_loss: 25.7334 - val_mae: 4.0495
Epoch 23/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.3101 - mae: 4.0144 - val_loss: 27.0407 - val_mae: 4.1485
Epoch 24/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.2968 - mae: 4.0140 - val_loss: 25.7049 - val_mae: 4.0441
Epoch 25/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.2940 - mae: 4.0128 - val_loss: 25.8029 - val_mae: 4.0542
Epoch 26/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 20s 3ms/step - loss: 25.2827 - mae: 4.0125 - val_loss: 25.9190 - val_mae: 4.0643
Epoch 27/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.2624 - mae: 4.0112 - val_loss: 25.7008 - val_mae: 4.0447
Epoch 28/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 25.2335 - mae: 4.0079 - val_loss: 25.6755 - val_mae: 4.0425
Epoch 29/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.2478 - mae: 4.0090 - val_loss: 26.9880 - val_mae: 4.1467
Epoch 30/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.1946 - mae: 4.0074 - val_loss: 25.5870 - val_mae: 4.0356
Epoch 31/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.2287 - mae: 4.0082 - val_loss: 25.6915 - val_mae: 4.0441
Epoch 32/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.2163 - mae: 4.0074 - val_loss: 25.9992 - val_mae: 4.0670
Epoch 33/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.1896 - mae: 4.0043 - val_loss: 25.6689 - val_mae: 4.0418
Epoch 34/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.1702 - mae: 4.0021 - val_loss: 27.5850 - val_mae: 4.1917
Epoch 35/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.1734 - mae: 4.0040 - val_loss: 25.6201 - val_mae: 4.0378
Epoch 36/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 22s 3ms/step - loss: 25.1473 - mae: 4.0002 - val_loss: 25.6426 - val_mae: 4.0386
Epoch 37/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.1551 - mae: 4.0010 - val_loss: 25.9624 - val_mae: 4.0637
Epoch 38/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.1474 - mae: 3.9998 - val_loss: 25.9428 - val_mae: 4.0631
Epoch 39/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.1008 - mae: 3.9970 - val_loss: 25.8177 - val_mae: 4.0549
Epoch 40/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.0923 - mae: 3.9956 - val_loss: 26.0205 - val_mae: 4.0687
Epoch 41/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.0678 - mae: 3.9942 - val_loss: 25.7174 - val_mae: 4.0435
Epoch 42/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.0528 - mae: 3.9935 - val_loss: 25.7226 - val_mae: 4.0440
Epoch 43/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.0432 - mae: 3.9922 - val_loss: 25.7442 - val_mae: 4.0445
Epoch 44/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 25.0291 - mae: 3.9919 - val_loss: 25.6960 - val_mae: 4.0447
Epoch 45/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.0340 - mae: 3.9916 - val_loss: 25.7282 - val_mae: 4.0467
Epoch 46/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 25.0145 - mae: 3.9910 - val_loss: 25.8348 - val_mae: 4.0558
Epoch 47/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 21s 3ms/step - loss: 25.0211 - mae: 3.9895 - val_loss: 25.8508 - val_mae: 4.0522
Epoch 48/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 24.9920 - mae: 3.9897 - val_loss: 25.7952 - val_mae: 4.0497
Epoch 49/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 19s 3ms/step - loss: 24.9783 - mae: 3.9852 - val_loss: 25.9141 - val_mae: 4.0601
Epoch 50/50
6000/6000 ━━━━━━━━━━━━━━━━━━━━ 18s 3ms/step - loss: 24.9602 - mae: 3.9842 - val_loss: 25.8091 - val_mae: 4.0512

In [95]:
y_pred = model4.predict(X_test_scaled)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step

In [97]:
y_pred.shape

(60000, 1)

In [98]:
y_pred = y_pred.flatten()

In [99]:
comparison = pd.DataFrame({'Actual': y_test.values[:10], 'Predicted': y_pred[:10]})
print(comparison)

      Actual  Predicted
0  71.326607  67.406708
1  74.775774  67.131699
2  66.361362  66.845261
3  71.182141  70.258461
4  60.550851  56.430889
5  44.119818  45.272991
6  51.569524  57.458534
7  59.987718  54.398434
8  63.416381  61.954746
9  68.868046  70.193100

Comparison **Table**

In [100]:
comparison_table = pd.DataFrame({
    'Model': ['Model 1', 'Model 2', 'Model 3', 'Model 4'],
    'Activation': ['ReLU', 'Tanh', 'Sigmoid', 'ReLU'],
    'Optimizer': ['Adam', 'SGD', 'RMSprop', 'Adam'],
    'Epochs': [20, 20, 20, 50],
    'Loss': [25.31, 26.51, 149.70, 24.96],
    'MAE': [4.01, 4.10, 9.77, 3.98],
    'Val_MAE': [4.08, 4.17, 9.75, 4.05]
})
comparison_table

     Model Activation Optimizer  Epochs    Loss   MAE  Val_MAE
0  Model 1       ReLU      Adam      20   25.31  4.01     4.08
1  Model 2       Tanh       SGD      20   26.51  4.10     4.17
2  Model 3    Sigmoid   RMSprop      20  149.70  9.77     9.75
3  Model 4       ReLU      Adam      50   24.96  3.98     4.05

**Conclusion**



*   Best model: Model 4 (ReLU activation, Adam optimizer, 50 epochs) — lowest loss aur MAE
*   ReLU ne Sigmoid se acha kaam kiya kyunki Sigmoid deep layers mein vanishing gradient problem create karta hai — Model 3 ka loss 149 par stuck ho gaya tha

*   Adam optimizer ne SGD se behtar perform kiya kyunki Adam adaptive learning rate use karta hai, jo tezi se aur stable convergence deta hai
*   20 se 50 epochs tak jaane se result thoda improve hua (loss 25.31 → 24.96), lekin farq chhota tha — model plateau ke qareeb hai

*  Training loss aur validation loss ek dusre ke qareeb rahe har model mein (Model 3 ke ilawa jo already fail ho gaya tha) — matlab overfitting nahi hui