In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
df.shape

(284807, 31)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:

df.duplicated().sum()

np.int64(1081)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(283726, 31)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 283726 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    283726 non-null  float64
 1   V1      283726 non-null  float64
 2   V2      283726 non-null  float64
 3   V3      283726 non-null  float64
 4   V4      283726 non-null  float64
 5   V5      283726 non-null  float64
 6   V6      283726 non-null  float64
 7   V7      283726 non-null  float64
 8   V8      283726 non-null  float64
 9   V9      283726 non-null  float64
 10  V10     283726 non-null  float64
 11  V11     283726 non-null  float64
 12  V12     283726 non-null  float64
 13  V13     283726 non-null  float64
 14  V14     283726 non-null  float64
 15  V15     283726 non-null  float64
 16  V16     283726 non-null  float64
 17  V17     283726 non-null  float64
 18  V18     283726 non-null  float64
 19  V19     283726 non-null  float64
 20  V20     283726 non-null  float64
 21  V21     283726 non-null  float64
 22  V22     283726 non-null  float64
 23  V23     283726 non-null  float64
 24  V24     283726 non-null  float64
 25  V25     283726 non-null  float64
 26  V26     283726 non-null  float64
 27  V27     283726 non-null  float64
 28  V28     283726 non-null  float64
 29  Amount  283726 non-null  float64
 30  Class   283726 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 69.3 MB

In [12]:
df['Class'].value_counts()

Class
0    283253
1       473
Name: count, dtype: int64

In [13]:
X = df.drop('Class', axis=1)
y = df['Class']

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train ,y_test = train_test_split(X,y , test_size=0.3, random_state=42, stratify= y)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
X_train_scaled.mean()

np.float64(-5.12791321559459e-18)

In [17]:
X_test_scaled .mean()

np.float64(-0.00096910775484928)

In [18]:
from imblearn.over_sampling import SMOTE

In [19]:
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

In [20]:
y_train_smote.value_counts()

Class
0    198277
1    198277
Name: count, dtype: int64

In [21]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [22]:
model1 = keras.Sequential([Dense(64, activation='relu', input_shape=(X_train_smote.shape[1],)),
                           Dense(32, activation='relu'),
                           Dense(16, activation='relu'),
                           Dense(1, activation='sigmoid')])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [23]:
model1.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,984 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,609 (18.00 KB)

 Trainable params: 4,609 (18.00 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model1.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
history1 = model1.fit(X_train_smote, y_train_smote, epochs=20, batch_size=32 , validation_split=0.2)

Epoch 1/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 26s 2ms/step - accuracy: 0.9948 - loss: 0.0174 - val_accuracy: 0.9997 - val_loss: 0.0030
Epoch 2/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9990 - loss: 0.0044 - val_accuracy: 1.0000 - val_loss: 6.3426e-04
Epoch 3/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9993 - loss: 0.0031 - val_accuracy: 1.0000 - val_loss: 5.7803e-04
Epoch 4/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9994 - loss: 0.0026 - val_accuracy: 0.9996 - val_loss: 0.0020
Epoch 5/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9995 - loss: 0.0020 - val_accuracy: 1.0000 - val_loss: 6.1472e-04
Epoch 6/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9996 - loss: 0.0020 - val_accuracy: 0.9994 - val_loss: 0.0017
Epoch 7/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9996 - loss: 0.0017 - val_accuracy: 1.0000 - val_loss: 1.4307e-04
Epoch 8/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9997 - loss: 0.0015 - val_accuracy: 1.0000 - val_loss: 3.7901e-04
Epoch 9/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 35s 4ms/step - accuracy: 0.9997 - loss: 0.0015 - val_accuracy: 0.9995 - val_loss: 0.0013
Epoch 10/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9997 - loss: 0.0014 - val_accuracy: 1.0000 - val_loss: 4.2357e-04
Epoch 11/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 3ms/step - accuracy: 0.9997 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 7.9753e-04
Epoch 12/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 7.0138e-05
Epoch 13/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 1.0000 - val_loss: 4.7078e-04
Epoch 14/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 1.0000 - val_loss: 9.8318e-05
Epoch 15/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9991 - val_loss: 0.0031
Epoch 16/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 17/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9998 - loss: 0.0010 - val_accuracy: 1.0000 - val_loss: 4.7490e-04
Epoch 18/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9998 - loss: 8.3254e-04 - val_accuracy: 1.0000 - val_loss: 1.1594e-04
Epoch 19/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9998 - loss: 9.1193e-04 - val_accuracy: 1.0000 - val_loss: 3.2319e-04
Epoch 20/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9998 - loss: 8.8127e-04 - val_accuracy: 0.9993 - val_loss: 0.0019

In [26]:
y_pred_prob = model1.predict(X_test_scaled)
y_pred = (y_pred_prob > 0.5).astype(int)

2660/2660 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step

In [27]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9992598510303343
Precision: 0.7762237762237763
Recall: 0.7816901408450704
F1-Score: 0.7789473684210526
Confusion Matrix:
 [[84944    32]
 [   31   111]]

In [28]:
model2 = keras.Sequential([Dense(64, activation='tanh', input_shape=(X_train_smote.shape[1],)),
                           Dense(32, activation='tanh'),
                           Dense(16, activation='tanh'),
                           Dense(1, activation='sigmoid')])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [29]:
model2.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [30]:
history2 = model2.fit(X_train_smote, y_train_smote, epochs=20, batch_size=32 , validation_split=0.2)

Epoch 1/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9701 - loss: 0.0838 - val_accuracy: 0.9766 - val_loss: 0.0586
Epoch 2/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9911 - loss: 0.0293 - val_accuracy: 0.9929 - val_loss: 0.0249
Epoch 3/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9960 - loss: 0.0158 - val_accuracy: 0.9991 - val_loss: 0.0083
Epoch 4/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9975 - loss: 0.0110 - val_accuracy: 0.9990 - val_loss: 0.0078
Epoch 5/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9982 - loss: 0.0085 - val_accuracy: 0.9998 - val_loss: 0.0050
Epoch 6/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9986 - loss: 0.0071 - val_accuracy: 0.9999 - val_loss: 0.0040
Epoch 7/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9988 - loss: 0.0062 - val_accuracy: 1.0000 - val_loss: 0.0042
Epoch 8/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9990 - loss: 0.0055 - val_accuracy: 1.0000 - val_loss: 0.0034
Epoch 9/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9992 - loss: 0.0049 - val_accuracy: 1.0000 - val_loss: 0.0036
Epoch 10/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9993 - loss: 0.0044 - val_accuracy: 1.0000 - val_loss: 0.0025
Epoch 11/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9993 - loss: 0.0039 - val_accuracy: 1.0000 - val_loss: 0.0019
Epoch 12/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9994 - loss: 0.0035 - val_accuracy: 1.0000 - val_loss: 0.0017
Epoch 13/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9994 - loss: 0.0032 - val_accuracy: 1.0000 - val_loss: 0.0018
Epoch 14/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9995 - loss: 0.0029 - val_accuracy: 0.9999 - val_loss: 0.0032
Epoch 15/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9995 - loss: 0.0027 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 16/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9996 - loss: 0.0025 - val_accuracy: 0.9992 - val_loss: 0.0037
Epoch 17/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 22s 2ms/step - accuracy: 0.9996 - loss: 0.0023 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 18/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9996 - loss: 0.0021 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 19/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.9997 - loss: 0.0019 - val_accuracy: 1.0000 - val_loss: 7.2622e-04
Epoch 20/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9997 - loss: 0.0018 - val_accuracy: 1.0000 - val_loss: 0.0016

In [31]:
y_pred_prob = model2.predict(X_test_scaled)
y_pred = (y_pred_prob > 0.5).astype(int)

2660/2660 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step

In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9987311731948589
Precision: 0.5904255319148937
Recall: 0.7816901408450704
F1-Score: 0.6727272727272727
Confusion Matrix:
 [[84899    77]
 [   31   111]]

In [33]:
model3 = keras.Sequential([Dense(64, activation='sigmoid', input_shape=(X_train_smote.shape[1],)),
                           Dense(32, activation='sigmoid'),
                           Dense(16, activation='sigmoid'),
                           Dense(1, activation='sigmoid')])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [34]:
model3.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [35]:
history3 = model3.fit(X_train_smote, y_train_smote, epochs=20, batch_size=32 , validation_split=0.2)

Epoch 1/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9708 - loss: 0.0774 - val_accuracy: 0.9958 - val_loss: 0.0139
Epoch 2/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9949 - loss: 0.0161 - val_accuracy: 0.9960 - val_loss: 0.0149
Epoch 3/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9971 - loss: 0.0106 - val_accuracy: 0.9965 - val_loss: 0.0113
Epoch 4/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9971 - loss: 0.0105 - val_accuracy: 1.0000 - val_loss: 0.0022
Epoch 5/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9974 - loss: 0.0099 - val_accuracy: 0.9998 - val_loss: 0.0042
Epoch 6/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9975 - loss: 0.0095 - val_accuracy: 1.0000 - val_loss: 0.0012
Epoch 7/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9976 - loss: 0.0092 - val_accuracy: 1.0000 - val_loss: 4.9533e-04
Epoch 8/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 23s 2ms/step - accuracy: 0.9978 - loss: 0.0087 - val_accuracy: 0.9990 - val_loss: 0.0075
Epoch 9/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9979 - loss: 0.0082 - val_accuracy: 1.0000 - val_loss: 6.4809e-04
Epoch 10/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9980 - loss: 0.0076 - val_accuracy: 0.9993 - val_loss: 0.0089
Epoch 11/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9982 - loss: 0.0072 - val_accuracy: 0.9997 - val_loss: 0.0041
Epoch 12/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 43s 3ms/step - accuracy: 0.9982 - loss: 0.0070 - val_accuracy: 0.9998 - val_loss: 0.0030
Epoch 13/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9983 - loss: 0.0066 - val_accuracy: 0.9999 - val_loss: 0.0054
Epoch 14/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9985 - loss: 0.0062 - val_accuracy: 1.0000 - val_loss: 0.0014
Epoch 15/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9987 - loss: 0.0057 - val_accuracy: 0.9982 - val_loss: 0.0082
Epoch 16/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9986 - loss: 0.0055 - val_accuracy: 0.9998 - val_loss: 0.0022
Epoch 17/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9987 - loss: 0.0053 - val_accuracy: 0.9975 - val_loss: 0.0129
Epoch 18/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9988 - loss: 0.0054 - val_accuracy: 1.0000 - val_loss: 0.0016
Epoch 19/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 25s 2ms/step - accuracy: 0.9988 - loss: 0.0051 - val_accuracy: 0.9997 - val_loss: 0.0030
Epoch 20/20
9914/9914 ━━━━━━━━━━━━━━━━━━━━ 24s 2ms/step - accuracy: 0.9989 - loss: 0.0049 - val_accuracy: 0.9998 - val_loss: 0.0033

In [36]:
y_pred_prob = model3.predict(X_test_scaled)
y_pred = (y_pred_prob > 0.5).astype(int)

2660/2660 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step

In [37]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall:", recall_score(y_test, y_pred))
print("F1-Score:", f1_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9980027726215371
Precision: 0.44656488549618323
Recall: 0.823943661971831
F1-Score: 0.5792079207920792
Confusion Matrix:
 [[84831   145]
 [   25   117]]

In [46]:
import joblib
joblib.dump(model1, 'model1_fraud_detection.pkl')
print("Model successfully save ho gaya!")

Model successfully save ho gaya!